A continuación te proporciono un resumen de los métodos más utilizados en la librería NumPy de Python:

    Creación de arreglos NumPy:
        numpy.array(): Crea un arreglo NumPy a partir de una lista o tupla.
        numpy.zeros(): Crea un arreglo NumPy lleno de ceros.
        numpy.ones(): Crea un arreglo NumPy lleno de unos.
        numpy.arange(): Crea un arreglo NumPy con valores espaciados uniformemente dentro de un intervalo.
        numpy.linspace(): Crea un arreglo NumPy con valores espaciados uniformemente entre dos límites.

    Acceso a los elementos de un arreglo NumPy:
        arreglo[index]: Accede a un elemento específico del arreglo.
        arreglo[start:end:step]: Accede a un subconjunto del arreglo mediante el uso de slicing.

    Operaciones matemáticas en arreglos NumPy:
        numpy.add(): Suma dos arreglos NumPy.
        numpy.subtract(): Resta dos arreglos NumPy.
        numpy.multiply(): Multiplica dos arreglos NumPy.
        numpy.divide(): Divide dos arreglos NumPy.
        numpy.dot(): Calcula el producto punto entre dos arreglos NumPy.

    Funciones matemáticas en arreglos NumPy:
        numpy.sin(): Calcula el seno de cada elemento en un arreglo NumPy.
        numpy.cos(): Calcula el coseno de cada elemento en un arreglo NumPy.
        numpy.exp(): Calcula la exponencial de cada elemento en un arreglo NumPy.
        numpy.log(): Calcula el logaritmo natural de cada elemento en un arreglo NumPy.

    Manipulación de arreglos NumPy:
        numpy.reshape(): Cambia la forma de un arreglo NumPy.
        numpy.transpose(): Transpone un arreglo NumPy.
        numpy.concatenate(): Combina dos arreglos NumPy a lo largo de un eje específico.

    Estadísticas en arreglos NumPy:
        numpy.mean(): Calcula la media de los elementos en un arreglo NumPy.
        numpy.median(): Calcula la mediana de los elementos en un arreglo NumPy.
        numpy.var(): Calcula la varianza de los elementos en un arreglo NumPy.
        numpy.std(): Calcula la desviación estándar de los elementos en un arreglo NumPy.

A continuación te proporciono algunos ejercicios utilizando métodos de la librería NumPy en programación orientada a objetos:

    Crear una clase ArrayOperations que tenga los siguientes métodos:
        __init__(self, array): Constructor que recibe un arreglo NumPy y lo asigna a una variable de instancia.
        add(self, other_array): Método que recibe otro arreglo NumPy y devuelve un nuevo arreglo NumPy que es la suma del arreglo de la instancia y el arreglo recibido.
        multiply(self, scalar): Método que recibe un escalar y devuelve un nuevo arreglo NumPy que es la multiplicación del arreglo de la instancia por el escalar recibido.

    Ejemplo de uso:

In [1]:
import numpy as np

class Matriz_operacion:

    def __init__(self, matriz) -> None:
        self.matriz= np.array(matriz)

    def sumar_matriz (self, agregar_matriz):
        return self.matriz + agregar_matriz
    
    def multiplicar_matriz (self, matriz_m):
        return np.dot(self.matriz, matriz_m.matriz)
        

matriz= Matriz_operacion([[1,2,3],
                          [1,2,3],
                          [1,2,3]])

matriz_2= Matriz_operacion([[5,2,1],
                            [0,3,1],
                            [7,2,3]])

matriz.sumar_matriz([[5,2,1],[0,3,1],[7,2,3]])

#matriz.multiplicar_matriz(matriz_2)

[5 7 9]
[2 4 6]


Crear una clase Statistics que tenga los siguientes métodos:

    __init__(self, array): Constructor que recibe un arreglo NumPy y lo asigna a una variable de instancia.
    mean(self): Método que devuelve la media del arreglo de la instancia.
    median(self): Método que devuelve la mediana del arreglo de la instancia.
    variance(self): Método que devuelve la varianza del arreglo de la instancia.
    std_deviation(self): Método que devuelve la desviación estándar del arreglo de la instancia.

Ejemplo de uso:

In [2]:
import numpy as np
class Operaciones_matrices:
    def __init__(self, matriz):
        self.matriz= np.array(matriz)

    def matriz_media (self, matriz_2):
        return np.mean(matriz_2.matriz)
    
    def matriz_mediana(self, matriz_2):
        return np.median(matriz_2.matriz)
    
    def matriz_varianza(self, matriz_2):
        return np.var(matriz_2.matriz)
    
    def matriz_desviacion (self, matriz_2):
        return np.std(matriz_2.matriz)
    


matriz= Operaciones_matrices([[1,2,3],
                          [1,2,3],
                          [1,2,3]])

matriz_2= Operaciones_matrices([[5,2,1],
                            [0,3,1],
                            [7,2,3]])

matriz.matriz_media(matriz_2)

matriz_2.matriz_mediana(matriz)

matriz_2.matriz_varianza(matriz)

matriz_2.matriz_desviacion(matriz)

0.816496580927726

Crear una clase MatrixOperations que tenga los siguientes métodos:

    __init__(self, matrix): Constructor que recibe una matriz NumPy y la asigna a una variable de instancia.
    transpose(self): Método que devuelve la matriz transpuesta del objeto de la instancia.
    dot(self, other_matrix): Método que recibe otra matriz NumPy y devuelve el producto matricial entre la matriz de la instancia y la matriz recibida.

Crear una clase MatrixOperations que tenga los siguientes métodos:

    __init__(self, matrix): Constructor que recibe una matriz NumPy y la asigna a una variable de instancia.
    transpose(self): Método que devuelve la matriz transpuesta del objeto de la instancia.
    dot(self, other_matrix): Método que recibe otra matriz NumPy y devuelve el producto matricial entre la matriz de la instancia y la matriz recibida.

Ejemplo de uso:Ejemplo de uso:

In [3]:
import numpy as np

class Operaciones_matrices:
    def __init__(self, matriz):
        self.matriz = np.array(matriz)
    
    """
    En el contexto de NumPy, T es un atributo que representa 
    la matriz transpuesta de un array. La propiedad T devuelve 
    la matriz transpuesta de la matriz o array en cuestión. 
    La transpuesta de una matriz intercambia sus filas por columnas, 
    es decir, refleja la matriz a lo largo de su diagonal principal.
    """
    def trasponer(self):
        return self.matriz.T
    
    def Producto_marcial(self, otra_matriz):
        return np.dot(self.matriz, otra_matriz)
    


matriz= Operaciones_matrices([[1,2,3],
                          [1,2,3],
                          [1,2,3]])

matriz_2= Operaciones_matrices([[5,2,1],
                            [0,3,1],
                            [7,2,3]])


matriz.trasponer()

#te puede salir este error
#matriz.Producto_marcial(matriz_2)

#corregido
#matriz.Producto_marcial(matriz_2.matriz)

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

Crear una clase VectorOperations que tenga los siguientes métodos:

    __init__(self, vector): Constructor que recibe un vector NumPy y lo asigna a una variable de instancia.
    magnitude(self): Método que devuelve la magnitud (norma) del vector de la instancia.
    dot(self, other_vector): Método que recibe otro vector NumPy y devuelve el producto escalar entre el vector de la instancia y el vector recibido.
    angle(self, other_vector): Método que recibe otro vector NumPy y devuelve el ángulo (en radianes) entre el vector de la instancia y el vector recibido.

Ejemplo de uso:

In [ ]:
import numpy as np

class VectorOperations:
    def __init__(self, vector):
        self.vector = np.array(vector)
    
    def magnitude(self):
        return np.linalg.norm(self.vector)
    
    def dot(self, other_vector):
        return np.dot(self.vector, other_vector)
    
    def angle(self, other_vector):
        return np.arccos(np.dot(self.vector, other_vector) / (np.linalg.norm(self.vector) * np.linalg.norm(other_vector)))

vector1 = VectorOperations([1, 2, 3])
vector2 = VectorOperations([4, 5, 6])

print(vector1.magnitude())  # 3.7416573867739413
print(vector1.dot(vector2.vector))  # 32
print(vector1.angle(vector2.vector))  # 0.22572612855273395


3.7416573867739413
32
0.2257261285527342
